name: Flutter Windows Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Find .exe path
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path build/windows/x64/runner/Release -Filter *.exe | Select-Object -First 1
          echo "EXE_PATH=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Get latest tag and bump
        id: bump_tag
        shell: pwsh
        run: |
          git fetch --tags
          $latestTag = git tag --list "v1.0.0+*" | Sort-Object -Descending | Select-Object -First 1
          if ($latestTag) {
            $buildNum = [int]($latestTag -replace 'v1\.0\.0\+', '')
            $newBuildNum = $buildNum + 1
          } else {
            $newBuildNum = 1
          }
          $newTag = "v1.0.0+$newBuildNum"
          echo "NEW_TAG=$newTag" | Out-File -FilePath $env:GITHUB_ENV -Append
          git tag $newTag
          git push origin $newTag

      - name: Zip Release folder
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath build/windows/x64/runner/Release/release_build.zip

      - name: Create Release and Upload zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body: "Automated Windows release for ${{ env.NEW_TAG }}\nCommit: ${{ github.sha }}"
          files: build/windows/x64/runner/Release/release_build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
